// Package apiauth implements FR-5.2: every management API request must be
// authenticated (bearer token) and authorized against the account (a
// business/tenant that may own several vhosts — internal/directory.Account)
// the caller's token is scoped to. This was never built in Phase 3 when
// internal/api's vhost/mailbox CRUD landed — a real, pre-existing
// functional gap this phase (TRD M5's NFR-SEC-4, "rate limiting and
// quotas on every abuse-relevant path... API requests") closes.
package apiauth

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"time"
)

// ErrNotFound is returned when a token lookup finds nothing.
var ErrNotFound = errors.New("apiauth: not found")

// DefaultPageSize/MaxPageSize bound ListTokensPage (FR-5.4) — the same
// values and reasoning as directory.DefaultVhostPageSize/MaxVhostPageSize,
// just declared separately since this is a different package.
const (
	DefaultPageSize = 100
	MaxPageSize     = 500
)

// TokenPrefix identifies an Envelope API token by sight (matching the
// Stripe/GitHub convention already used elsewhere — webhook.Sign's
// "sha256=<hex>" signatures) so a leaked token is recognizable in logs,
// scanners, and secret-detection tooling.
const TokenPrefix = "env_"

// Token is an issued API credential. AccountID is the owning Account's ID
// (internal/directory.Account — a business/tenant that owns one or more
// vhosts) it's scoped to; empty means an admin token, authorized against
// every account (FR-5.2's "the account(s) the caller's token is scoped
// to" — an admin token's set is "all of them"). Deliberately keyed by ID,
// not name: apiauth.Token is only ever compared against internal/api's own
// :accountId route params — using the ID directly avoids an extra
// GetAccount lookup on every authenticated request. The raw secret is
// never stored — only TokenHash — so a database read can't leak usable
// credentials.
type Token struct {
	ID        string
	AccountID string // "" = admin/global scope
	Label     string
	CreatedAt time.Time
}

// Store is the token persistence + authentication contract.
type Store interface {
	// CreateToken persists a new token record under tokenHash (see
	// HashToken) and returns it.
	CreateToken(ctx context.Context, id, accountID, label, tokenHash string) (Token, error)

	// Authenticate looks up the token matching tokenHash. ok is false if
	// no matching, non-revoked token exists.
	Authenticate(ctx context.Context, tokenHash string) (Token, bool, error)

	// ListTokens returns every one of accountID's tokens, unbounded (never
	// admin tokens — those are listed by passing "" only from an
	// admin-authorized caller, enforced by internal/api, not by this
	// Store). Kept unbounded rather than replaced by ListTokensPage: no
	// internal caller currently needs "every token" the way
	// Dispatcher.Enqueue/DataController.Export need every subscription/
	// mailbox, but the same asymmetry (an admin listing endpoint should be
	// paginated; an internal correctness-critical enumeration should not
	// silently truncate) is why both methods exist rather than one.
	ListTokens(ctx context.Context, accountID string) ([]Token, error)

	// ListTokensPage returns up to limit of accountID's tokens (FR-5.4),
	// cursor-paginated the same way directory.Service.ListVhosts is — see
	// that method's doc for the pattern. TokenController.ListTokens (the
	// API handler) calls this.
	ListTokensPage(ctx context.Context, accountID, cursor string, limit int) ([]Token, error)

	// RevokeToken deletes accountID's token id. accountID is a mandatory
	// predicate (FR-1.5), the same as every other account-scoped Store
	// method in this codebase: revoking id under the wrong account fails
	// exactly as if id didn't exist. An admin token (accountID "") can only
	// be revoked by passing accountID "" — internal/api enforces that only
	// an authenticated admin caller may do so.
	RevokeToken(ctx context.Context, accountID, id string) error
}

// GenerateToken returns a fresh, high-entropy raw token (returned to the
// caller exactly once — the API never stores or re-displays it, only
// TokenHash) and its hash (what actually gets persisted).
func GenerateToken() (raw, hash string, err error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", "", fmt.Errorf("apiauth: generate token: %w", err)
	}
	raw = TokenPrefix + base64.RawURLEncoding.EncodeToString(buf)
	return raw, HashToken(raw), nil
}

// HashToken deterministically hashes a raw token for storage/lookup.
// SHA-256, not bcrypt: unlike a user-chosen password, a token generated by
// GenerateToken already has 256 bits of entropy, so a fast, indexable hash
// (WHERE token_hash = ?) is the right tool — bcrypt's deliberate slowness
// defends against low-entropy guessing, which doesn't apply here, and
// would make every authenticated request pay bcrypt's cost.
func HashToken(raw string) string {
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:])
}

// ConstantTimeEqual compares two strings without leaking timing
// information about where they first differ — used to compare a bearer
// token against the bootstrap admin token (env-var-sourced, so it can't be
// looked up by hash the way issued tokens are).
func ConstantTimeEqual(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}
