// Package metrics defines the Prometheus counters/gauges/histograms
// Envelope's pipeline updates as work happens — the full envelope_*
// metric set TRD §6.5 names (NFR-OBS-1). cmd/envelope/main.go wires a
// /metrics endpoint (promhttp.Handler against the default registry every
// metric here registers against) unconditionally, on every role, since a
// dashboard/scrape target shouldn't have to know which --roles subset a
// given process happens to run.
package metrics

import "github.com/prometheus/client_golang/prometheus"

var (
	// SpamScorerUnavailableTotal counts inbound messages accepted via
	// FR-2.6's fail-open path because rspamd was unreachable.
	SpamScorerUnavailableTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "envelope_spam_scorer_unavailable_total",
		Help: "Inbound messages accepted via the FR-2.6 fail-open path because rspamd was unreachable.",
	})

	// MessagesReceivedTotal counts inbound messages that completed the
	// FR-2.4/2.5 filter pipeline with a non-reject verdict, labeled by
	// that verdict ("accept" or "quarantine" — reject isn't counted here
	// since FR-2.5 stores nothing for a rejected message; it's visible
	// instead as SMTP 5xx responses at the protocol layer).
	MessagesReceivedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "envelope_messages_received_total",
		Help: "Inbound messages accepted or quarantined, labeled by verdict.",
	}, []string{"verdict"})

	// QueueDepth is the current count of outbound jobs not yet delivered
	// or dead-lettered (internal/queue.Backend.Count), sampled
	// periodically by internal/deliverer.Deliverer.Run — see that
	// method's doc for why a gauge updated on a timer, not incremented/
	// decremented inline at Enqueue/Complete/Fail, is the correct/
	// drift-proof way to keep this accurate.
	QueueDepth = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "envelope_queue_depth",
		Help: "Current number of outbound jobs not yet delivered or dead-lettered.",
	})

	// DeliveryLatencySeconds measures one outbound delivery *attempt*'s
	// duration (MX lookup through SMTP transaction, ending in success or
	// a terminal/retryable failure) — internal/deliverer.Deliverer.handle.
	// Not the same thing as TRD §6.1's "time from enqueue to first
	// delivery attempt" target, which would need an enqueue timestamp
	// queue.Job doesn't currently carry; that's a named, tracked gap
	// (docs/ENVELOPE.md Phase 6), not silently approximated by this
	// metric under the same name.
	DeliveryLatencySeconds = prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:    "envelope_delivery_latency_seconds",
		Help:    "Duration of one outbound delivery attempt (MX lookup through SMTP transaction).",
		Buckets: prometheus.DefBuckets,
	})

	// BouncesTotal counts DSNs generated by internal/deliverer (FR-3.6:
	// permanent failure or attempts exhausted).
	BouncesTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "envelope_bounces_total",
		Help: "Outbound messages that generated a bounce (DSN) — permanent failure or attempts exhausted.",
	})

	// WebhookDeliveryFailuresTotal counts failed webhook delivery
	// attempts (internal/webhook.Dispatcher) — every non-2xx response or
	// transport error, not just final dead-letters.
	WebhookDeliveryFailuresTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "envelope_webhook_delivery_failures_total",
		Help: "Failed webhook delivery attempts (non-2xx response or transport error).",
	})

	// RetentionPurgedTotal counts messages deleted by internal/retention's
	// NFR-COMP-1 purge sweep for having aged past their vhost's (or the
	// platform default) retention window.
	RetentionPurgedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "envelope_retention_purged_total",
		Help: "Messages deleted by the NFR-COMP-1 retention purge for exceeding their retention window.",
	})
)

func init() {
	prometheus.MustRegister(
		SpamScorerUnavailableTotal,
		MessagesReceivedTotal,
		QueueDepth,
		DeliveryLatencySeconds,
		BouncesTotal,
		WebhookDeliveryFailuresTotal,
		RetentionPurgedTotal,
	)
}
